import { useState, useRef } from 'react';
import { Copy, Check, ChevronLeft, ChevronRight, Download, Columns2, LayoutList, Globe, ImageIcon, FileText, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import type { MultiModelContent } from '@/types';
import { useToast } from '@/hooks/use-toast';
import { Skeleton } from '@/components/ui/skeleton';
import { formatModelName } from '@/lib/utils';
import { useChatStore } from '@/features/chat/store/chatStore';
import type { GenerationActivityType } from '@/features/chat/types';

interface MultiModelResponseProps {
  content: MultiModelContent;
  models: string[];
}

// Activity indicator component
const ActivityIndicator = ({ activity, modelName }: { activity: GenerationActivityType; modelName: string }) => {
  if (!activity) return null;
  
  const getActivityConfig = () => {
    switch (activity) {
      case 'searching_web':
        return { icon: Globe, text: 'Searching web', textColor: 'text-blue-500', bgColor: 'bg-blue-500/10' };
      case 'analyzing_image':
        return { icon: ImageIcon, text: 'Analyzing image', textColor: 'text-purple-500', bgColor: 'bg-purple-500/10' };
      case 'analyzing_pdf':
        return { icon: FileText, text: 'Analyzing PDF', textColor: 'text-orange-500', bgColor: 'bg-orange-500/10' };
      case 'generating':
      default:
        return { icon: Loader2, text: 'Generating', textColor: 'text-primary', bgColor: 'bg-primary/10' };
    }
  };
  
  const config = getActivityConfig();
  const Icon = config.icon;
  
  return (
    <span className={`inline-flex items-center gap-1 text-[10px] font-medium ${config.textColor} ${config.bgColor} px-1.5 py-0.5 rounded animate-pulse`}>
      <Icon className={`w-3 h-3 ${activity === 'generating' ? 'animate-spin' : ''}`} />
      {config.text}
    </span>
  );
};

// Shared markdown components extracted to avoid re-creation
const markdownComponents = {
  code({ inline, className, children, ...props }: any) {
    const match = /language-(\w+)/.exec(className || '');
    return !inline && match ? (
      <div className="my-2 rounded-lg overflow-hidden">
        <SyntaxHighlighter style={vscDarkPlus} language={match[1]} PreTag="div" {...props}>
          {String(children).replace(/\n$/, '')}
        </SyntaxHighlighter>
      </div>
    ) : (
      <code className="bg-muted/60 px-1.5 py-0.5 rounded text-[12px] font-mono" {...props}>
        {children}
      </code>
    );
  },
  p: ({ children }: any) => <p className="mb-2.5 last:mb-0 leading-relaxed">{children}</p>,
  ul: ({ children }: any) => <ul className="list-disc list-outside ml-4 mb-2.5 space-y-1">{children}</ul>,
  ol: ({ children }: any) => <ol className="list-decimal list-outside ml-4 mb-2.5 space-y-1">{children}</ol>,
  li: ({ children }: any) => <li className="leading-relaxed">{children}</li>,
  strong: ({ children }: any) => <strong className="font-semibold">{children}</strong>,
  h1: ({ children }: any) => <h1 className="text-base font-bold mb-2 mt-3 first:mt-0">{children}</h1>,
  h2: ({ children }: any) => <h2 className="text-sm font-bold mb-1.5 mt-2.5 first:mt-0">{children}</h2>,
  h3: ({ children }: any) => <h3 className="text-sm font-semibold mb-1.5 mt-2 first:mt-0">{children}</h3>,
  table: ({ children }: any) => (
    <div className="my-2.5 overflow-x-auto rounded-lg border border-border/40">
      <table className="w-full text-xs border-collapse">{children}</table>
    </div>
  ),
  thead: ({ children }: any) => <thead className="bg-muted/50">{children}</thead>,
  tbody: ({ children }: any) => <tbody className="divide-y divide-border/30">{children}</tbody>,
  tr: ({ children }: any) => <tr className="hover:bg-muted/20 transition-colors">{children}</tr>,
  th: ({ children }: any) => (
    <th className="px-2.5 py-1.5 text-left text-[11px] font-semibold text-foreground/80 border-b border-border/40 whitespace-nowrap">
      {children}
    </th>
  ),
  td: ({ children }: any) => <td className="px-2.5 py-1.5 text-[12px] text-foreground/90">{children}</td>,
};

const getProviderColor = (model: string): string => {
  const modelLower = model.toLowerCase();
  if (modelLower.includes('gpt') || modelLower.includes('openai')) return 'from-emerald-500 to-teal-600';
  if (modelLower.includes('gemini') || modelLower.includes('google')) return 'from-blue-500 to-indigo-600';
  if (modelLower.includes('claude') || modelLower.includes('anthropic')) return 'from-orange-400 to-amber-600';
  if (modelLower.includes('perplexity')) return 'from-purple-500 to-violet-600';
  if (modelLower.includes('qwen')) return 'from-cyan-500 to-blue-600';
  if (modelLower.includes('cohere')) return 'from-rose-500 to-pink-600';
  return 'from-slate-500 to-slate-600';
};

const DISCLAIMER_TEXT = 'This response is generated by the selected model, not by Zebvo AI. Zebvo AI is not responsible for any inaccurate information, hallucinations, or mistakes that may appear in the response. For better accuracy, try multiple models and compare the results. Once you find the output you like, deselect the other models and use a single model consistently to get better results.';

export const MultiModelResponse = ({ content, models }: MultiModelResponseProps) => {
  const [viewMode, setViewMode] = useState<'single' | 'compare'>('compare');
  const [currentIndex, setCurrentIndex] = useState(0);
  const [copiedModel, setCopiedModel] = useState<string | null>(null);
  const hasAnimatedRef = useRef(false);
  const { toast } = useToast();
  const isLoading = useChatStore((s) => s.isLoading);
  const generationActivityType = useChatStore((s) => s.generationActivityType);

  // Helper to check if a specific model is still generating
  const isModelGenerating = (model: string) => isLoading && (!content[model] || content[model].trim() === '');
  
  // Check if ALL models are still generating (used for overall container states)
  const allModelsGenerating = isLoading && models.every((m) => !content[m] || content[m].trim() === '');

  // Only apply entrance animation on first mount
  const shouldAnimate = !hasAnimatedRef.current;
  if (shouldAnimate) {
    hasAnimatedRef.current = true;
  }

  const handleCopy = (model: string) => {
    navigator.clipboard.writeText(content[model]);
    setCopiedModel(model);
    toast({ description: 'Copied to clipboard', duration: 2000 });
    setTimeout(() => setCopiedModel(null), 2000);
  };

  const handleDownload = (model: string) => {
    const blob = new Blob([content[model]], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${formatModelName(model)}-response.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ description: 'Response downloaded', duration: 2000 });
  };

  const currentModel = models[currentIndex];
  const currentContent = content[currentModel] || '';

  // View toggle component (shared between both views)
  const ViewToggle = (
    <div className="inline-flex items-center p-0.5 bg-muted/40 rounded-lg border border-border/30">
      <button
        onClick={() => setViewMode('single')}
        className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium transition-all duration-fast ease-gentle ${
          viewMode === 'single' ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'
        }`}
      >
        <LayoutList className="w-3.5 h-3.5" />
        Single
      </button>
      <button
        onClick={() => setViewMode('compare')}
        className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium transition-all duration-fast ease-gentle ${
          viewMode === 'compare' ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'
        }`}
      >
        <Columns2 className="w-3.5 h-3.5" />
        Compare
      </button>
    </div>
  );

  return (
    <div className={`w-full mt-16 ${shouldAnimate ? 'appear-smooth' : ''}`}>
      {/* ===== SINGLE VIEW ===== */}
      <div
        className="transition-all duration-moderate ease-gentle"
        style={{
          display: viewMode === 'single' ? 'block' : 'none',
        }}
      >
        <div className="px-4 sm:px-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">{ViewToggle}</div>
            {models.length > 1 && (
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground">
                  {currentIndex + 1} of {models.length}
                </span>
                <div className="flex items-center gap-0.5">
                  <button
                    onClick={() => setCurrentIndex((prev) => (prev - 1 + models.length) % models.length)}
                    className="w-7 h-7 rounded-full bg-muted/50 hover:bg-muted flex items-center justify-center transition-all duration-fast ease-gentle hover:scale-hover active:scale-press"
                  >
                    <ChevronLeft className="w-4 h-4 text-muted-foreground" />
                  </button>
                  <button
                    onClick={() => setCurrentIndex((prev) => (prev + 1) % models.length)}
                    className="w-7 h-7 rounded-full bg-muted/50 hover:bg-muted flex items-center justify-center transition-all duration-fast ease-gentle hover:scale-hover active:scale-press"
                  >
                    <ChevronRight className="w-4 h-4 text-muted-foreground" />
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Response Card - keyed for smooth model switch */}
          <div className="max-w-3xl">
            <div key={currentModel} className="flex gap-3 animate-fade-in">
              {/* Avatar */}
              <div
                className={`w-8 h-8 rounded-full bg-gradient-to-br ${getProviderColor(currentModel)} flex items-center justify-center flex-shrink-0 shadow-sm`}
              >
                <span className="text-white font-semibold text-xs">
                  {formatModelName(currentModel).charAt(0)}
                </span>
              </div>

              <div className="flex-1 min-w-0">
                {/* Model name with activity indicator */}
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-medium text-foreground/80">
                    {formatModelName(currentModel)}
                  </span>
                  {isModelGenerating(currentModel) && !currentContent && (
                    <ActivityIndicator activity={generationActivityType} modelName={currentModel} />
                  )}
                  {isModelGenerating(currentModel) && currentContent && (
                    <span className="text-[10px] font-medium text-primary bg-primary/10 px-1.5 py-0.5 rounded animate-pulse">
                      typing...
                    </span>
                  )}
                </div>

                {/* Content - shows skeleton only if this specific model hasn't started, otherwise streams live */}
                <div
                  className="bg-card rounded-xl border border-border/30 p-4 shadow-sm"
                  style={{
                    minHeight: isModelGenerating(currentModel) ? '220px' : 'auto',
                    transition: 'min-height 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
                  }}
                >
                  {isModelGenerating(currentModel) ? (
                    <div className="space-y-3 py-1">
                      <Skeleton className="h-4 w-[90%]" />
                      <Skeleton className="h-4 w-[75%]" />
                      <Skeleton className="h-4 w-[85%]" />
                      <Skeleton className="h-4 w-[60%]" />
                      <Skeleton className="h-4 w-[80%]" />
                      <Skeleton className="h-4 w-[70%]" />
                    </div>
                  ) : (
                    <div
                      className="prose prose-sm max-w-none text-foreground text-[13px] leading-relaxed overflow-x-auto"
                      style={{
                        animation: 'fade-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
                      }}
                    >
                      <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                        {currentContent}
                      </ReactMarkdown>
                    </div>
                  )}
                </div>

                {/* Actions */}
                <div className="flex items-center gap-1 mt-2">
                  <button
                    onClick={() => handleCopy(currentModel)}
                    className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs text-muted-foreground hover:bg-muted/50 transition-all duration-fast ease-gentle active:scale-press"
                  >
                    {copiedModel === currentModel ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-primary" />
                        <span className="text-primary">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => handleDownload(currentModel)}
                    className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs text-muted-foreground hover:bg-muted/50 transition-all duration-fast ease-gentle active:scale-press"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download</span>
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="mt-4 px-3 py-3 rounded-lg bg-muted/50 border border-border/50 max-w-3xl">
            <p className="text-xs text-muted-foreground leading-relaxed">
              <span className="font-medium text-foreground/80">Note:</span> {DISCLAIMER_TEXT}
            </p>
          </div>
        </div>
      </div>

      {/* ===== COMPARE VIEW ===== */}
      <div
        className="transition-all duration-moderate ease-gentle"
        style={{
          display: viewMode === 'compare' ? 'block' : 'none',
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-2 sm:mb-3 px-3 sm:px-6">
          <div className="flex items-center gap-2 sm:gap-3">
            {ViewToggle}
            <span className="text-[11px] sm:text-xs text-muted-foreground">
              {models.length} models
            </span>
          </div>
          <div className="hidden sm:flex items-center gap-1.5 text-xs text-muted-foreground/60">
            <ChevronLeft className="w-3 h-3" />
            <span>Scroll to compare</span>
            <ChevronRight className="w-3 h-3" />
          </div>
        </div>

        {/* Scrollable Cards Container */}
        <div className="relative">
          {/* Gradient fades */}
          <div className="absolute left-0 top-0 bottom-0 w-6 bg-gradient-to-r from-background to-transparent z-10 pointer-events-none" />
          <div className="absolute right-0 top-0 bottom-0 w-6 bg-gradient-to-l from-background to-transparent z-10 pointer-events-none" />

          <div className="overflow-x-auto scroll-smooth pb-2 [&::-webkit-scrollbar]:hidden" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
            <div
              className={`flex gap-2.5 sm:gap-3 px-3 sm:px-6 ${shouldAnimate ? 'stagger-cards' : ''}`}
              style={{ minWidth: 'min-content' }}
            >
              {models.map((model, idx) => {
                const response = content[model] || '';
                const thisModelGenerating = isModelGenerating(model);
                const hasContent = response && response.trim() !== '';
                return (
                  <div
                    key={model}
                    className="w-[260px] sm:w-[340px] lg:w-[380px] flex-shrink-0 flex flex-col bg-card rounded-xl border border-border/40 shadow-sm overflow-hidden hover:shadow-md hover:border-border/60 hover:-translate-y-1 transition-all duration-normal ease-spring"
                    style={{ minHeight: '180px', maxHeight: '400px' }}
                  >
                    {/* Card Header */}
                    <div className="flex-shrink-0 h-11 px-3 border-b border-border/20 bg-muted/20 flex items-center gap-2.5">
                      <div className={`w-2 h-2 rounded-full bg-gradient-to-br ${getProviderColor(model)} ${thisModelGenerating && !hasContent ? 'animate-pulse' : ''}`} />
                      <div className="flex-1 min-w-0">
                        <span className="text-[13px] font-medium text-foreground truncate block">
                          {formatModelName(model)}
                        </span>
                      </div>
                      {thisModelGenerating && !hasContent && (
                        <ActivityIndicator activity={generationActivityType} modelName={model} />
                      )}
                      {thisModelGenerating && hasContent && (
                        <span className="text-[10px] font-medium text-primary bg-primary/10 px-1.5 py-0.5 rounded animate-pulse">
                          typing...
                        </span>
                      )}
                      <span className="text-[10px] font-medium text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                        #{idx + 1}
                      </span>
                    </div>

                    {/* Response Content - shows live content as it streams */}
                    <div className={`flex-1 p-3 min-h-0 overflow-y-auto`}>
                      <div className="text-[13px] leading-[1.6] text-foreground">
                        {!hasContent ? (
                          <div className="space-y-2.5 py-1">
                            <Skeleton className="h-3.5 w-[95%]" />
                            <Skeleton className="h-3.5 w-[80%]" />
                            <Skeleton className="h-3.5 w-[88%]" />
                            <Skeleton className="h-3.5 w-[70%]" />
                            <Skeleton className="h-3.5 w-[85%]" />
                            <Skeleton className="h-3.5 w-[65%]" />
                          </div>
                        ) : (
                          <div className={thisModelGenerating ? '' : 'animate-fade-in'}>
                            <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                              {response}
                            </ReactMarkdown>
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Card Footer */}
                    <div className="flex-shrink-0 h-9 px-2 border-t border-border/15 bg-muted/10 flex items-center gap-1">
                      <button
                        onClick={() => handleCopy(model)}
                        className="h-7 px-2 rounded-md hover:bg-muted/60 transition-all duration-fast ease-gentle flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground active:scale-press"
                        title="Copy response"
                      >
                        {copiedModel === model ? (
                          <Check className="w-3.5 h-3.5 text-primary" />
                        ) : (
                          <Copy className="w-3.5 h-3.5" />
                        )}
                        <span className="hidden sm:inline">Copy</span>
                      </button>
                      <button
                        onClick={() => handleDownload(model)}
                        className="h-7 px-2 rounded-md hover:bg-muted/60 transition-all duration-fast ease-gentle flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground ml-auto active:scale-press"
                        title="Download response"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span className="hidden sm:inline">Download</span>
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <p className="text-xs text-muted-foreground mt-4 px-3 sm:px-6">
          <span className="font-medium">Note:</span> {DISCLAIMER_TEXT}
        </p>
      </div>
    </div>
  );
};
