import { useState } from 'react';
import { ChevronLeft, ChevronRight, Grid3x3, ArrowLeft, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { MultiModelContent } from '@/types';
import { useToast } from '@/hooks/use-toast';
import { formatModelName } from '@/lib/utils';

interface MultiModelImageResponseProps {
  content: MultiModelContent;
  models: string[];
}

export const MultiModelImageResponse = ({ content, models }: MultiModelImageResponseProps) => {
  const [viewMode, setViewMode] = useState<'carousel' | 'compare'>('carousel');
  const [currentIndex, setCurrentIndex] = useState(0);
  const { toast } = useToast();

  const handleDownload = async (url: string, modelName: string) => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const downloadUrl = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = `${modelName.replace(/\s+/g, '-')}-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(downloadUrl);
      document.body.removeChild(a);
      
      toast({
        description: 'Image downloaded successfully',
        duration: 2000,
      });
    } catch (error) {
      toast({
        description: 'Failed to download image',
        variant: 'destructive',
        duration: 2000,
      });
    }
  };

  const handleNext = () => {
    setCurrentIndex((prev) => (prev + 1) % models.length);
  };

  const handlePrev = () => {
    setCurrentIndex((prev) => (prev - 1 + models.length) % models.length);
  };

  if (viewMode === 'compare') {
    return (
      <div className="space-y-4">
        <div className="flex items-center justify-end">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setViewMode('carousel')}
            className="text-sm"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Carousel
          </Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {models.map((model) => {
            const imageUrl = content[model];
            const isError = typeof imageUrl === 'string' && imageUrl.startsWith('Error:');
            
            return (
              <div key={model} className="bg-white/80 backdrop-blur-sm rounded-lg border border-border/30 p-3 space-y-2 shadow-sm">
                <div className="flex items-center justify-between gap-2">
                  <span className="text-sm font-medium text-muted-foreground">{formatModelName(model)}</span>
                  {!isError && (
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 hover:bg-muted/50"
                      onClick={() => handleDownload(imageUrl, model)}
                    >
                      <Download className="w-4 h-4" />
                    </Button>
                  )}
                </div>
                {isError ? (
                  <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-700">
                    {imageUrl}
                  </div>
                ) : (
                  <img 
                    src={imageUrl} 
                    alt={`Generated by ${model}`}
                    className="rounded-lg w-full shadow-md"
                    onError={(e) => {
                      console.error(`Failed to load image from ${model}:`, imageUrl);
                      const target = e.target as HTMLImageElement;
                      target.alt = `Failed to load image from ${model}`;
                    }}
                    loading="lazy"
                  />
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  // Carousel view
  const currentModel = models[currentIndex];
  const currentImageUrl = content[currentModel];
  const isError = typeof currentImageUrl === 'string' && currentImageUrl.startsWith('Error:');

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-end">
        <Button
          variant="outline"
          size="sm"
          onClick={() => setViewMode('compare')}
          className="text-sm"
        >
          <Grid3x3 className="w-4 h-4 mr-2" />
          Compare
        </Button>
      </div>

      <div className="bg-white/80 backdrop-blur-sm rounded-lg border border-border/30 p-3 space-y-2 shadow-sm">
        <div className="flex items-center justify-between gap-2">
          <span className="text-sm font-medium text-muted-foreground">
            {formatModelName(currentModel)}
          </span>
          <div className="flex items-center gap-2">
            {!isError && (
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 hover:bg-muted/50"
                onClick={() => handleDownload(currentImageUrl, currentModel)}
              >
                <Download className="w-4 h-4" />
              </Button>
            )}
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 hover:bg-muted/50"
                onClick={handlePrev}
                disabled={models.length <= 1}
              >
                <ChevronLeft className="w-4 h-4" />
              </Button>
              <span className="text-xs text-muted-foreground min-w-[3rem] text-center">
                {currentIndex + 1} of {models.length}
              </span>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 hover:bg-muted/50"
                onClick={handleNext}
                disabled={models.length <= 1}
              >
                <ChevronRight className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>

        {isError ? (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-700">
            {currentImageUrl}
          </div>
        ) : (
          <img 
            src={currentImageUrl} 
            alt={`Generated by ${currentModel}`}
            className="rounded-lg w-full shadow-md"
            onError={(e) => {
              console.error(`Failed to load image from ${currentModel}:`, currentImageUrl);
              const target = e.target as HTMLImageElement;
              target.alt = `Failed to load image from ${currentModel}`;
            }}
            loading="lazy"
          />
        )}
      </div>
    </div>
  );
};