import jsPDF from 'jspdf';

interface ExportOptions {
  title?: string;
  model?: string;
  wordCount?: number;
}

/**
 * Convert markdown to plain text for PDF
 */
const markdownToPlainText = (markdown: string): string => {
  return markdown
    // Remove headers but keep text
    .replace(/^#{1,6}\s+/gm, '')
    // Remove bold/italic markers
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/_([^_]+)_/g, '$1')
    // Convert links to text with URL
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)')
    // Remove code blocks
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`([^`]+)`/g, '$1')
    // Remove horizontal rules
    .replace(/^---+$/gm, '')
    // Clean up extra whitespace
    .replace(/\n{3,}/g, '\n\n')
    .trim();
};

/**
 * Export research content as a formatted PDF
 */
export const exportResearchAsPDF = (
  content: string,
  options: ExportOptions = {}
): void => {
  const { title = 'Deep Research Report', model = 'Perplexity Deep Research', wordCount } = options;
  
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper to add new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, yPosition);
  yPosition += 12;

  // Metadata line
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const metaText = `Generated by ${model} | ${date}${wordCount ? ` | ${wordCount.toLocaleString()} words` : ''}`;
  doc.text(metaText, margin, yPosition);
  yPosition += 8;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Process content by sections
  const lines = content.split('\n');
  
  for (const line of lines) {
    const trimmedLine = line.trim();
    
    if (!trimmedLine) {
      yPosition += 4;
      continue;
    }

    // Handle headings
    if (trimmedLine.startsWith('## ')) {
      checkPageBreak(15);
      yPosition += 6;
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      const headingText = trimmedLine.replace(/^##\s+/, '').replace(/\*\*/g, '');
      doc.text(headingText, margin, yPosition);
      yPosition += 8;
      doc.setFont('helvetica', 'normal');
      continue;
    }

    if (trimmedLine.startsWith('### ')) {
      checkPageBreak(12);
      yPosition += 4;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      const headingText = trimmedLine.replace(/^###\s+/, '').replace(/\*\*/g, '');
      doc.text(headingText, margin, yPosition);
      yPosition += 7;
      doc.setFont('helvetica', 'normal');
      continue;
    }

    if (trimmedLine.startsWith('# ')) {
      checkPageBreak(18);
      yPosition += 8;
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      const headingText = trimmedLine.replace(/^#\s+/, '').replace(/\*\*/g, '');
      doc.text(headingText, margin, yPosition);
      yPosition += 10;
      doc.setFont('helvetica', 'normal');
      continue;
    }

    // Handle bullet points
    if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
      checkPageBreak(8);
      doc.setFontSize(11);
      const bulletText = trimmedLine.replace(/^[-*]\s+/, '• ').replace(/\*\*/g, '');
      const splitText = doc.splitTextToSize(bulletText, contentWidth - 5);
      doc.text(splitText, margin + 3, yPosition);
      yPosition += splitText.length * 5 + 2;
      continue;
    }

    // Handle numbered lists
    const numberedMatch = trimmedLine.match(/^(\d+)\.\s+/);
    if (numberedMatch) {
      checkPageBreak(8);
      doc.setFontSize(11);
      const listText = trimmedLine.replace(/\*\*/g, '');
      const splitText = doc.splitTextToSize(listText, contentWidth - 5);
      doc.text(splitText, margin + 3, yPosition);
      yPosition += splitText.length * 5 + 2;
      continue;
    }

    // Regular paragraph
    checkPageBreak(8);
    doc.setFontSize(11);
    const cleanText = trimmedLine
      .replace(/\*\*([^*]+)\*\*/g, '$1')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1');
    const splitText = doc.splitTextToSize(cleanText, contentWidth);
    doc.text(splitText, margin, yPosition);
    yPosition += splitText.length * 5 + 3;
  }

  // Add page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // Generate filename
  const timestamp = new Date().toISOString().split('T')[0];
  const sanitizedTitle = title
    .replace(/[^a-z0-9\s-]/gi, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 40);
  
  doc.save(`${sanitizedTitle}-${timestamp}.pdf`);
};

export default exportResearchAsPDF;
